name: miscere_varius_ifab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  sensors_plus: ^5.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/compass/
